# Generated by Django 5.1.4 on 2025-01-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOverview',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_date', models.DateTimeField(verbose_name='activity date')),
                ('activity_name', models.CharField(max_length=120)),
                ('average_hr', models.FloatField(null=True)),
                ('start_lat', models.FloatField(null=True)),
                ('start_lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('athlete_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=120)),
                ('acces_token', models.CharField(max_length=64, unique=True)),
                ('refresh_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name='expiration date')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='activity timestamp')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('heart_rate', models.FloatField(verbose_name='heart rate')),
                ('distance', models.FloatField(verbose_name='distance')),
                ('elevation', models.FloatField(verbose_name='elevation')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strivers.activityoverview')),
            ],
        ),
        migrations.AddField(
            model_name='activityoverview',
            name='athlete_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strivers.athlete'),
        ),
    ]
