# Generated by Django 5.1.4 on 2025-01-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='acces_token',
            new_name='access_token',
        ),
    ]
