# Generated by Django 5.1.4 on 2025-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strivers', '0003_alter_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(default='Jesse', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(default='Ivers', max_length=120),
            preserve_default=False,
        ),
    ]
