# Generated by Django 5.1.3 on 2025-01-30 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strivers', '0005_alter_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 30, 21, 40, 8, 775940, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='scope',
            field=models.BooleanField(default=False),
        ),
    ]
